### ISSUE TITLE
get_rmsd, get_tfd only compare first conformers, which can result in unexpected RMSD/TFD

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/yammbs#28]
I often write my own hacky scripts that add onto the IB functionality, so this might not be a bug that you would expect to run into in normal use of IB -- but it also seems fairly straightforward to safeguard against. In functions like get_rmsd:

https://github.com/mattwthompson/ib/blob/77cb48573dd496b7bfeb9ce3200ef036976bac9b/ibstore/analysis.py#L90C1-L113C6

the RMSD is outsourced to OpenEye by creating an OEMol. Since we provide both the MM and QM conformer geometries as arguments with `reference` and `target`, I expected a comparison from said MM and QM geometries. However, if the molecule already has an existing conformer on it, I *think* that's the only geometry that actually gets compared -- looking at the OERMSD docs doesn't actually tell me anything about which conformers it looks at. In rdkit's `GetTFDBetweenMolecules`, the docs say that despite confID1 and confID2 having default arguments of -1, the default is the first conformer. I haven't looked at the code to check but I do get TFDs of 0.0 as well!

I think a simple fix would just be clearing the conformers of the copied Molecule.

**Comment by mattwthompson** [comment]
Clearing conformers in that function sounds good

That function seems to only ever be called internally with a `Molecule` constructed [here](https://github.com/mattwthompson/ib/blob/77cb48573dd496b7bfeb9ce3200ef036976bac9b/ibstore/_store.py#L634) that doesn't have existing conformers when it's sent. But `ibstore.analysis.get_rmsd` is a public function and getting the RMSD between conformers other than between what was passed sure seems like an unwelcome surprise indeed!

**Comment by mattwthompson** [comment]
I think I've done this in #29, though it'd be nice to also get this into the toolkit so I don't have to check for `None` myself
