### ISSUE TITLE
Caching code written for old QCPortal

### ISSUE THREAD

**Issue by amcisaac** [openforcefield/yammbs#38]
The caching code in YAMMBs seems to be written for the old QCPortal, and crashes due to this call in `CachedResultCollection`:

```
energy = qcarchive_record.get_final_energy() * hartree2kcalmol
```

It seems like the new `OptimizationRecord` doesn't have that function `get_final_energy()` (the definition of the class is [here](https://github.com/MolSSI/QCFractal/blob/2b1f5b1deb0ea25205b54c53a743f2bb71c150ef/qcportal/qcportal/optimization/record_models.py#L50)).

**Comment by mattwthompson** [comment]
These are 0.54 changes?

**Comment by amcisaac** [comment]
It's definitely a change made between 0.15.8 and 0.53 (which was the version that threw me the error), but I think it was just a change made with the big 0.50 release. It's definitely present in 0.15.8 ([here](https://github.com/MolSSI/QCFractal/blob/v0.15.8.1/qcfractal/interface/models/records.py#L435)) but not present (as far as i can tell) in 0.50 ([here](https://github.com/MolSSI/QCFractal/blob/v0.50/qcportal/qcportal/optimization/record_models.py#L43))
