### ISSUE TITLE
Allow cosmetic attributes in all force fields

### ISSUE THREAD

**Issue by amcisaac** [openforcefield/yammbs#48]
I recently got an error stemming from `_minimize._lazy_load_force_field` rejecting my force field because it had cosmetic attributes. I went to take a look at the [code](https://github.com/openforcefield/yammbs/blob/main/yammbs/_minimize.py#L36), and it looks like cosmetic attributes are allowed if the force field name starts with `openff`, but not for other `offxml` force fields. It's easy to rename my force field to start with `openff`, or just strip the cosmetic attributes, but I wanted to bring it up in case that's not intentional behavior.

**Comment by mattwthompson** [comment]
Good catch, I didn't consider that a development iteration might start with `openff` but that seems to be what the code assumes

I suppose this branch could just be removed - allowing cosmetic attributes by default should be (relatively) safe and loading plugins should be (relatively) quick, I think

https://github.com/openforcefield/yammbs/blob/f87fd451b2518320b8b79001da072475afc57977/yammbs/_minimize.py#L53

**Comment by amcisaac** [comment]
Yes, I think you could either remove the branch at line 62 (`if force_field_name.startswith("openff"):`) or edit line 65 to `ForceField(force_field_name, load_plugins=True, allow_cosmetic_attributes=True)`
