### ISSUE TITLE
Crashing with undefined stereo in 0.1.0beta0 test

### ISSUE THREAD

**Issue by ntBre** [openforcefield/yammbs#72]
I updated yammbs-dataset-submission to use the new input models (which was quite easy!), but it's crashing when trying to load a `MoleculeStore` from the `QCArchiveDataset`. [Workflow](https://github.com/openforcefield/yammbs-dataset-submission/actions/runs/11408656163/job/31747514113)

I think this just needs an `allow_undefined_stereo=True` arg.

https://github.com/openforcefield/yammbs/blob/ce588dafa51b13dc2f548b1ef99568a20bd0f4e1/yammbs/_store.py#L546

**Comment by mattwthompson** [comment]
Oof, this shouldn't have slipped through the cracks. The patch sounds fine to me, but I'd really like a test as well
